name: Deploy Lambda
on:
  push:
    branches:
      - master
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Lint and Syntax Check
        run: |
          python -m py_compile *.py
          pip install flake8
          flake8 . --exclude=venv,.venv,env,bin,lib,deps --count --statistics  --ignore=E501,E127,E128,W503,E126
      - name: Run Unit Tests
        # keep pytest out of production, only used for testing
        run: | 
          pip install pytest
          pip install -r requirements.txt
          pytest test_city_weather_data.py

        # steps needed for container deployment
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: weather-aggregator
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build the image using the GitHub commit SHA as a unique tag
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          # Optional: Also tag and push as 'latest' for easier reference
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Update Lambda Function with New Image
        run: |
          aws lambda update-function-code \
          --function-name weatherAggregator \
          --image-uri ${{ steps.login-ecr.outputs.registry }}/weather-aggregator:${{ github.sha }}

      - name: Update Lambda Environment Variables
        run: |
          aws lambda update-function-configuration \
          --function-name weatherAggregator \
          --environment "Variables={WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }},AWS_REGION=eu-north-1}"